apiVersion: rbac.authorization.k8s.io/v1
kind: clusterRoleBinding
metadata:
  name: platform-admin-binding 
subjects:
- kind: User 
  name: platform-admin
roleRef:
  kind: ClusterRole
  name: cluster-admin 
  apiGroups: rbac.rbac.authorization.k8s.io


