apiVersion: v1
kind: ConfigMap 
metadata:
  name: app-config 
data:
  DB_HOST: mysql
  DB_PORT: "3306"

## configmap in pod
env: 
- name: DB_HOST
  valueFrom:
    configMapRef:
      name: app-config
      key: DB_HOST

## env
env: 
- name: BACKEND_URL
  value: http://backend 

## configmap
kind: ConfigMap 
data:
  DB_HOST: mysql

---
## configmap for managed db
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config 
  namespace: dev
data:
  DB_HOST: mydb.cle.ap-south-1.rds.amazonaws.com 
  DB_PORT: "3306"
  DB_NAME: appdb