apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod 
  labels:
    app: web
spec: 
  containers:
    - name: nginx
      image: nginx:latest
      ports:
      - containerPort: 80

## kubectl apply -f pod.yaml
---

apiVersion: v1
kind: Pod 
metadata:
  name: website
  namespace: dev 
  labels:
    name: web
    application: my-app 
    version: "v31"
    release: "r42"
    stage: production
spec:
  containers:
    - name: web-server 
      image: nginx
      ports: 
      - containerPort: 80
      resources:
        requests:
          cpu: "250m" 
          memory: "256Mi"  
        limits:
          memory: "500Mi"
          cpu: "500m" 

---
 
