apiVersion: rbac.authorization.k8s.io/v1 
kind: Role 
metadata:
  namespace: dev 
  name: read-pods 
rules:
- apiGroups:
    - [""]
  resources: ["pods"]
  verbs: ["get","list"]

---
## rbac for cicd
apiVersion: rbac.authorization.k8s.io/v1 
kind: ClusterRole
metadata:
  name: deployer-role 
rules:
- apiGroups: ["," "apps","networking.k8s.io"]
  resources: ["deployments","Services", "ingress"]
  verbs: ["get","list", "apply", "create","update"]

## bound via clusterRoleBinding
---
