kind: Secret 
type: Opaque
data:
  DB_PASSWORD: cjfljg=989poj

---
apiVersion: v1
kind: Secret 
metadata: 
  name: db-secret 
  namespace: dev
type: Opaque
data: 
  DB_USER: FLAJFLSDJFLSD # admin
  DB_PASSWORD: dlfjsjf # password