kind: ServiceAccount
apiVersion: v1
metadata:
  name: aws-load-balancer-controller 
  namespace: kube-system 
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<ACC_ID>:role/alb-ingress-role 

## this binds 
## pod -> serviceaccount -> iam role

## backend serviceaccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa 
  namespace: prod

## used in deployment
serviceAccountName: backend-sa
 